### PR TITLE
WIP: BC-12 # PHP files start with a single `?><?php\n`

### PR DESCRIPTION
**Pull request by jokeyrhyme**
### Changed

- BC-12: PHP files start with a single `?><?php\n` (#13, @jokeyrhyme)

    - this ensures your IDE of choice will properly highlight / autocomplete PHP code

- updated to [blinkmobile/json-as-files](https://github.com/blinkmobile/json-as-files.js) 1.1.1

    - makes a few disk writes unnecessary, so we skip them

### Code Review Notes

- skip / ignore commits for BC-10, BC-13 and BC-11, they'll be rebased out

### CODE REVIEW

**Comment by jokeyrhyme** [comment]
Review by @rayron and @rachelhughes revealed a few issues:

- `\n` is not a cross-platform line-ending character, so causes Windows vs Unix weirdness

    - maybe checking for any white-space is better than specifically checking for `\n`

- should this PHP tag injection be performed by the CLI, or by the remote service?

- should this PHP tag injection be performed as an option instead of by default?

**Comment by simonmarklar** [comment]
i've not found `\n` to cause weirdness unless i'm using notepad, I think decent code editors can handle it on windows.

There is an option to set git to fix line endings, which is probably a good thing for project consistancy, but i'm not sure we can assume everyones using git, data3 might be using tfs, for example.

However now i'm wondering about the need for this - everyone who codes PHP knows that that you have to start with `<?php` or `<?` ... and looking at the code i think that there's a problem with the detection. I thought I saw a test case that handled the problem but I must of been mistaken

perhaps we leave off the auto updating to `?><?php\n` ???

**Comment by jokeyrhyme** [comment]
Yeah, it's why I renamed this to "WIP: ...". I suspect this work will be suspended indefinitely.

**Comment by jokeyrhyme** [comment]
There doesn't seem to be any demand for this functionality, and there are open questions about how to accomplish it in a reliable and consistent way.

**Pull request closed without merging**
