### PR TITLE
BC-22 # pull and deploy check scope matches content

### PR DESCRIPTION
**Pull request by jokeyrhyme**
### Fixed

- BC-22: `pull` and `deploy` commands abort immediately if the target scope does not match the "name" field in the primary JSON file (#16, @jokeyrhyme)

    - prevents further data-loss in cases where local files are corrupted or scope has been unexpectedly changed

- BC-22: GET requests are considered a failure if the result's ID doesn't match the requested ID

    - prevents corruption of local files

- the progress bar during `deploy` works again (broken during BC-18, #15)

### Code Review Notes

- [`String#endsWith()`](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/String/endsWith) is nice :)

    - I checked and it's in Node 4.x LTS and up

### CODE REVIEW

**Comment by simonmarklar** [comment]
Code looks fine.

Is there anywhere else that an anwerspace id could mismatch the scope? are interactions tagged with the answerspace they are for or is all that handled somewhere else ?

**Comment by jokeyrhyme** [comment]
I'm tackling IDs in BC-21. This covers the scope === name bit, and BC-21 will cover name => id bit.

**Comment by simonmarklar** [comment]
awesome. LGTM :+1:

**Comment by simonmarklar** [comment]
LGTM :+1:

**Pull request merged**
